version: "2"
plugins:
  duplication:
    enabled: true
    config:
      languages:
        python:
          python_version: 3
          mass_threshold: 60
  bandit:
    enabled: false
  editorconfig:
    enabled: true
  markdownlint:
    enabled: true
  pep8:
    enabled: true
  radon:
    enabled: true
    config:
      python_version: 3
  sonar-python:
    enabled: true
